# Generated by Django 3.2.7 on 2021-12-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_tweet_store_tweet_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet_store',
            name='n_words',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='tweet_store',
            name='p_words',
            field=models.TextField(default=' '),
        ),
    ]
